/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user and receive access token
         */
        post: operations["v1UsersLoginCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout current user and invalidate current token
         */
        post: operations["v1UsersLogoutCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/logoutall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout all
         * @description Logout user from all devices and invalidate all tokens
         */
        post: operations["v1UsersLogoutallCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the user profile */
        get: operations["v1UsersProfileRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register a new user account */
        post: operations["v1UsersRegisterCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Request password reset token for user email */
        post: operations["v1UsersResetPasswordCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/update-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Update user password using reset token */
        post: operations["v1UsersUpdatePasswordCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BadRequestResponseFromLoginSerializer: {
            /** @description No data returned */
            responseData?: string | null;
            responseErrors: components["schemas"]["ResponseErrorsLoginSerializer"];
        };
        BadRequestResponseFromRequestRegisterUserSerializer: {
            /** @description No data returned */
            responseData?: string | null;
            responseErrors: components["schemas"]["ResponseErrorsRequestRegisterUserSerializer"];
        };
        BadRequestResponseFromRequestResetPasswordSerializer: {
            /** @description No data returned */
            responseData?: string | null;
            responseErrors: components["schemas"]["ResponseErrorsRequestResetPasswordSerializer"];
        };
        BadRequestResponseFromRequestUpdatePasswordUserSerializer: {
            /** @description No data returned */
            responseData?: string | null;
            responseErrors: components["schemas"]["ResponseErrorsRequestUpdatePasswordUserSerializer"];
        };
        Login: {
            /** @description Enter your username below to login to your account */
            username: string;
            password: string;
        };
        LoginResponse: {
            /** @description Authentication token for subsequent requests */
            token: string;
            /**
             * Format: date-time
             * @description Token expiration timestamp
             */
            expiry: string;
        };
        LogoutAllResponse: {
            /**
             * @description Logout confirmation message
             * @default Successfully logged out.
             */
            detail: string;
        };
        RequestRegisterUser: {
            /** Format: email */
            email: string;
            password: string;
            username: string;
        };
        RequestResetPassword: {
            /** Format: email */
            email: string;
        };
        RequestUpdatePasswordUser: {
            token: string;
            password: string;
        };
        ResponseErrorsLoginSerializer: {
            /** @description Non-field errors */
            nonFieldErrors: string[] | null;
            /** @description Enter your username below to login to your account */
            username: string[] | null;
            password: string[] | null;
        };
        ResponseErrorsRequestRegisterUserSerializer: {
            /** @description Non-field errors */
            nonFieldErrors: string[] | null;
            email: string[] | null;
            password: string[] | null;
            username: string[] | null;
        };
        ResponseErrorsRequestResetPasswordSerializer: {
            /** @description Non-field errors */
            nonFieldErrors: string[] | null;
            email: string[] | null;
        };
        ResponseErrorsRequestUpdatePasswordUserSerializer: {
            /** @description Non-field errors */
            nonFieldErrors: string[] | null;
            token: string[] | null;
            password: string[] | null;
        };
        ResponseProfile: {
            firstName: string;
            lastName: string;
            email: string;
        };
        ResponseSuccessFromSingleResponseProfileSerializer: {
            /** @description No error returned */
            responseErrors?: string | null;
            responseData: components["schemas"]["ResponseProfile"];
        };
        SuccessResponseFromMessages: {
            responseData: string[];
            /** @description No errors returned */
            responseErrors?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1UsersLoginCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Login successful, access token provided in response and cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponseFromLoginSerializer"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1UsersLogoutCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User logged out successfully, access token cookie cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseFromMessages"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1UsersLogoutallCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User logged out from all devices, all tokens invalidated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutAllResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1UsersProfileRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body means the endpoint responded successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseSuccessFromSingleResponseProfileSerializer"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1UsersRegisterCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["RequestRegisterUser"];
                "multipart/form-data": components["schemas"]["RequestRegisterUser"];
                "application/json": components["schemas"]["RequestRegisterUser"];
            };
        };
        responses: {
            /** @description User account created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseFromMessages"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponseFromRequestRegisterUserSerializer"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1UsersResetPasswordCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["RequestResetPassword"];
                "multipart/form-data": components["schemas"]["RequestResetPassword"];
                "application/json": components["schemas"]["RequestResetPassword"];
            };
        };
        responses: {
            /** @description Password reset token generated and sent (always returns 200 for security) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseFromMessages"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponseFromRequestResetPasswordSerializer"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1UsersUpdatePasswordCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["RequestUpdatePasswordUser"];
                "multipart/form-data": components["schemas"]["RequestUpdatePasswordUser"];
                "application/json": components["schemas"]["RequestUpdatePasswordUser"];
            };
        };
        responses: {
            /** @description Password updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseFromMessages"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponseFromRequestUpdatePasswordUserSerializer"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
